name: release
on:
  push:
    tags:
      - "v[0-9]+\\.[0-9]+\\.[0-9]+"
jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: set RELEASE_VERSION env
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
      
      - name: set MAJOR_VERSION env
        run: |
          MAJOR_VERSION="${RELEASE_VERSION:0:2}"
          echo "MAJOR_VERSION=$MAJOR_VERSION" >> $GITHUB_ENV

      - name: echo env var
        run: |
          echo "Release version: ${{ env.RELEASE_VERSION }}"
          echo "Major version: ${{ env.MAJOR_VERSION }}"

      - name: ensure image version is set to release version
        run: |
          image=$(yq '.runs.image' action.yml)
          echo "Image version: $image"
          [[ "$image" == *"${{ env.RELEASE_VERSION }}" ]]

      - name: login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: |
            VERSION=${{ env.RELEASE_VERSION }}
          provenance: false
          sbom: false
          tags: |
            ghcr.io/vladopajic/go-test-coverage:${{ env.RELEASE_VERSION }}
            ghcr.io/vladopajic/go-test-coverage:${{ env.MAJOR_VERSION }}
            ghcr.io/vladopajic/go-test-coverage:latest

      - name: point major version tag latest release version
        uses: actions/publish-action@v0.4.0
        with:
          source-tag: ${{ env.RELEASE_VERSION }}